service: users-api

frameworkVersion: "2"

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"

functions:
  getUser:
    handler: src/Lambdas/getUser.handler
    events:
      - http:
          path: /user/{id}
          method: get

plugins:
  - serverless-plugin-typescript
